Update for list-based configuration
Consensys/ansible-role-teku pull request #4
Opened 2020-05-19 05:24 UTC by EdJoJob

2020-05-22 01:18 UTC, benjamincburns commented on filter_plugins/teku_filters.py
> +        return f'''"{'" "'.join(escaped_teku_env_opts)}"'''
lolwut?

2020-05-22 01:19 UTC, benjamincburns commented on filter_plugins/teku_filters.py
> +        return f'''"{'" "'.join(escaped_teku_env_opts)}"'''
https://www.python.org/dev/peps/pep-0498/

TIL!

2020-05-22 01:22 UTC, benjamincburns requested changes

2020-05-22 01:22 UTC, benjamincburns commented on filter_plugins/teku_filters.py
> +        return f'''"{'" "'.join(escaped_teku_env_opts)}"'''
This is super not readable, sadly... Perhaps just add a comment like `# quote the individual items`?

2020-06-29 06:42 UTC, joshuafernandes commented
closing this one coz its been superceeded by #7 - if it looks like a list, and quacks like a list...

2020-06-29 06:42 UTC, closed without merging